In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pickle

## 加载数据

In [2]:
origin_train = pd.read_csv('../01_data/used_car_train_20200313.csv', sep=' ')
origin_test = pd.read_csv('../01_data/used_car_testB_20200421.csv', sep=' ')

In [3]:
result = pd.DataFrame()
result['SaleID'] = origin_test['SaleID']

In [4]:
origin_train = origin_train[['regDate', 'creatDate']]
origin_test = origin_test[['regDate', 'creatDate']]

In [5]:
train_data = None
with open('../02_user_data/train_v1.pk', mode='rb') as f:
    train_data = pickle.load(f)
train_data

,name,model,brand,bodyType,fuelType,gearbox,power,kilometer,notRepairedDamage,regionCode,...,v_5,v_6,v_7,v_8,v_9,v_10,v_11,v_12,v_13,v_14
0,736,30.0,6,1.0,0.0,0.0,60,12.5,0,1046,...,0.235676,0.101988,0.129549,0.022816,0.097462,-2.881803,2.804097,-2.420821,0.795292,0.914762
1,2262,40.0,1,2.0,0.0,0.0,0,15.0,0,4366,...,0.264777,0.121004,0.135731,0.026597,0.020582,-4.900482,2.096338,-1.030483,-1.722674,0.245522
2,14874,115.0,15,1.0,0.0,0.0,163,12.5,0,2806,...,0.251410,0.114912,0.165147,0.062173,0.027075,-4.846749,1.803559,1.565330,-0.832687,-0.229963
3,71865,109.0,10,0.0,0.0,1.0,193,15.0,0,434,...,0.274293,0.110300,0.121964,0.033395,0.000000,-4.509599,1.285940,-0.501868,-2.438353,-0.478699
4,111080,110.0,5,1.0,0.0,0.0,68,5.0,0,6977,...,0.228036,0.073205,0.091880,0.078819,0.121534,-1.896240,0.910783,0.931110,2.834518,1.923482
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
149995,163978,121.0,10,4.0,0.0,1.0,163,15.0,0,4576,...,0.280264,0.000310,0.048441,0.071158,0.019174,1.988114,-2.983973,0.589167,-1.304370,-0.302592
149996,184535,116.0,11,0.0,0.0,0.0,125,10.0,0,2826,...,0.253217,0.000777,0.084079,0.099681,0.079371,1.839166,-2.774615,2.553994,0.924196,-0.272160
149997,147587,60.0,11,1.0,1.0,0.0,90,6.0,0,3302,...,0.233353,0.000705,0.118872,0.100118,0.097914,2.439812,-1.630677,2.290197,1.891922,0.414931
149998,45907,34.0,10,3.0,1.0,0.0,156,15.0,0,1877,...,0.256369,0.000252,0.081479,0.083558,0.081498,2.075380,-2.633719,1.414937,0.431981,-1.659014
149999,177672,19.0,28,6.0,0.0,1.0,193,12.5,0,235,...,0.284475,0.000000,0.040072,0.062543,0.025819,1.978453,-3.179913,0.031724,-1.483350,-0.342674

In [6]:
test_data = None
with open('../02_user_data/test_v1.pk', mode='rb') as f:
    test_data = pickle.load(f)
test_data

,name,model,brand,bodyType,fuelType,gearbox,power,kilometer,notRepairedDamage,regionCode,...,v_5,v_6,v_7,v_8,v_9,v_10,v_11,v_12,v_13,v_14
0,133777,67.0,0,1.0,0.0,0.0,101,15.0,0,5019,...,0.236520,0.000241,0.105319,0.046233,0.094522,3.619512,-0.280607,-2.019761,0.978828,0.803322
1,61206,19.0,6,2.0,0.0,0.0,73,6.0,0,1505,...,0.261518,0.000000,0.120323,0.046784,0.035385,2.997376,-1.406705,-1.020884,-1.349990,-0.200542
2,67829,5.0,5,4.0,0.0,0.0,120,5.0,0,1776,...,0.261691,0.090836,0.000000,0.079655,0.073586,-3.951084,-0.433467,0.918964,1.634604,1.027173
3,8892,22.0,9,1.0,0.0,0.0,58,15.0,0,26,...,0.236050,0.101777,0.098950,0.026830,0.096614,-2.846788,2.800267,-2.524610,1.076819,0.461610
4,76998,46.0,6,0.0,NaN,0.0,116,15.0,0,738,...,0.257000,0.000000,0.066732,0.057771,0.068852,2.839010,-1.659801,-0.924142,0.199423,0.451014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,111443,4.0,4,0.0,NaN,1.0,150,15.0,0,5564,...,0.263668,0.000292,0.141804,0.076393,0.039272,2.072901,-2.531869,1.716978,-1.063437,0.326587
49996,152834,65.0,1,0.0,0.0,0.0,179,4.0,0,5220,...,0.255310,0.000991,0.155868,0.108425,0.067841,1.358504,-3.290295,4.269809,0.140524,0.556221
49997,132531,4.0,4,0.0,0.0,1.0,147,12.5,0,3795,...,0.262933,0.000318,0.141872,0.071968,0.042966,2.165658,-2.417885,1.370612,-1.073133,0.270602
49998,143405,40.0,1,4.0,0.0,1.0,176,15.0,0,61,...,0.282106,0.000023,0.067483,0.067526,0.009006,2.030114,-2.939244,0.569078,-1.718245,0.316379
49999,78202,32.0,8,1.0,0.0,0.0,0,3.0,0,4158,...,0.231449,0.103947,0.096027,0.062328,0.110180,-3.689090,2.032376,0.109157,2.202828,0.847469

## 缺失值填充

In [7]:
temp = train_data.isnull().sum()
temp = temp[temp > 0]
temp

model          1
bodyType    4506
fuelType    8680
gearbox     5981
dtype: int64

***这里用众数填充***

In [8]:
for feature in list(temp.index):
    train_data[feature].fillna(train_data[feature].mode()[0], inplace=True)
    test_data[feature].fillna(test_data[feature].mode()[0], inplace=True)

In [9]:
train_data.isnull().sum()

name                 0
model                0
brand                0
bodyType             0
fuelType             0
gearbox              0
power                0
kilometer            0
notRepairedDamage    0
regionCode           0
price                0
v_0                  0
v_1                  0
v_2                  0
v_3                  0
v_4                  0
v_5                  0
v_6                  0
v_7                  0
v_8                  0
v_9                  0
v_10                 0
v_11                 0
v_12                 0
v_13                 0
v_14                 0
dtype: int64

In [10]:
test_data.isnull().sum()

name                 0
model                0
brand                0
bodyType             0
fuelType             0
gearbox              0
power                0
kilometer            0
notRepairedDamage    0
regionCode           0
v_0                  0
v_1                  0
v_2                  0
v_3                  0
v_4                  0
v_5                  0
v_6                  0
v_7                  0
v_8                  0
v_9                  0
v_10                 0
v_11                 0
v_12                 0
v_13                 0
v_14                 0
dtype: int64

## 特征处理

#### 时间相关（regDate, creatDate）

时间多尺度处理

In [11]:
origin_train['regDate'] = pd.to_datetime(origin_train['regDate'])
train_data['regDate_Y'] = origin_train['regDate'].dt.year
train_data['regDate_M'] = origin_train['regDate'].dt.month
train_data['regDate_D'] = origin_train['regDate'].dt.day
train_data['regDate_Diff'] = (origin_train['regDate'] - np.min(origin_train['regDate'])).dt.days

In [12]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 30 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   name               150000 non-null  int64
 1   model              150000 non-null  float64
 2   brand              150000 non-null  int64
 3   bodyType           150000 non-null  float64
 4   fuelType           150000 non-null  float64
 5   gearbox            150000 non-null  float64
 6   power              150000 non-null  int64
 7   kilometer          150000 non-null  float64
 8   notRepairedDamage  150000 non-null  int64
 9   regionCode         150000 non-null  int64
 10  price              150000 non-null  int64
 11  v_0                150000 non-null  float64
 12  v_1                150000 non-null  float64
 13  v_2                150000 non-null  float64
 14  v_3                150000 non-null  float64
 15  v_4                150000 non-null  float64
 16  v_5                150000 non-null  float64
 17  v_6                150000 non-null  float64
 18  v_7                150000 non-null  float64
 19  v_8                150000 non-null  float64
 20  v_9                150000 non-null  float64
 21  v_10               150000 non-null  float64
 22  v_11               150000 non-null  float64
 23  v_12               150000 non-null  float64
 24  v_13               150000 non-null  float64
 25  v_14               150000 non-null  float64
 26  regDate_Y          150000 non-null  int64
 27  regDate_M          150000 non-null  int64
 28  regDate_D          150000 non-null  int64
 29  regDate_Diff       150000 non-null  int64
dtypes: float64(20), int64(10)
memory usage: 34.3 MB

In [13]:
origin_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   regDate    50000 non-null  int64
 1   creatDate  50000 non-null  int64
dtypes: int64(2)
memory usage: 781.4 KB

In [14]:
origin_test['regDate'] = pd.to_datetime(origin_test['regDate'])
test_data['regDate_Y'] = origin_test['regDate'].dt.year
test_data['regDate_M'] = origin_test['regDate'].dt.month
test_data['regDate_D'] = origin_test['regDate'].dt.day
test_data['regDate_Diff'] = (origin_test['regDate'] - np.min(origin_test['regDate'])).dt.days

In [15]:
origin_train['creatDate'] = pd.to_datetime(origin_train['creatDate'])
train_data['creatDate_Y'] = origin_train['creatDate'].dt.year
train_data['creatDate_M'] = origin_train['creatDate'].dt.month
train_data['creatDate_D'] = origin_train['creatDate'].dt.day
train_data['creatDate_Diff'] = (origin_train['creatDate'] - np.min(origin_train['creatDate'])).dt.days

In [16]:
origin_test['creatDate'] = pd.to_datetime(origin_test['creatDate'])
test_data['creatDate_Y'] = origin_test['creatDate'].dt.year
test_data['creatDate_M'] = origin_test['creatDate'].dt.month
test_data['creatDate_D'] = origin_test['creatDate'].dt.day
test_data['creatDate_Diff'] = (origin_test['creatDate'] - np.min(origin_test['creatDate'])).dt.days

In [17]:
test_data.isnull().sum()

name                 0
model                0
brand                0
bodyType             0
fuelType             0
gearbox              0
power                0
kilometer            0
notRepairedDamage    0
regionCode           0
v_0                  0
v_1                  0
v_2                  0
v_3                  0
v_4                  0
v_5                  0
v_6                  0
v_7                  0
v_8                  0
v_9                  0
v_10                 0
v_11                 0
v_12                 0
v_13                 0
v_14                 0
regDate_Y            0
regDate_M            0
regDate_D            0
regDate_Diff         0
creatDate_Y          0
creatDate_M          0
creatDate_D          0
creatDate_Diff       0
dtype: int64

In [18]:
# 模型创建 - XGBoost
import xgboost as xgb
param = {
    #'objective' : 'reg:linear',
    'eval_metric' : 'auc',
    'tree_method' : 'gpu_hist',
    'max_depth' : 6,
    'colsample_bytree': 0.8,
    'min_child_samples' : 3,
    'subsample' : 0.8,
    'reg_lambda' : 0.5,
    'learning_rate' : 0.05,
    'n_estimators' : 2000,
}
model = xgb.XGBRegressor(
    max_depth=6, learning_rate=0.05, n_estimators=300, 
    objective='reg:linear', tree_method='gpu_hist', 
    subsample=0.8, colsample_bytree=0.8, 
    min_child_samples=3, eval_metric='auc', reg_lambda=0.5
)

In [19]:
X_train = train_data.drop(columns=['price'])
Y_test = train_data['price']
X_test = test_data

In [20]:
model.fit(X_train, Y_test)

[09:27:35] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/objective/regression_obj.cu:171: reg:linear is now deprecated in favor of reg:squarederror.
[09:27:35] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/learner.cc:573:
Parameters: { "min_child_samples" } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.8, eval_metric='auc',
             gamma=0, gpu_id=0, importance_type='gain',
             interaction_constraints='', learning_rate=0.05, max_delta_step=0,
             max_depth=6, min_child_samples=3, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=300, n_jobs=6,
             num_parallel_tree=1, objective='reg:linear', random_state=0,
             reg_alpha=0, reg_lambda=0.5, scale_pos_weight=1, subsample=0.8,
             tree_method='gpu_hist', validate_parameters=1, verbosity=None)

In [21]:
y_predictions = model.predict(X_test)
y_predictions

C:\ProgramData\Anaconda3\lib\site-packages\xgboost\data.py:112: UserWarning: Use subset (sliced data) of np.ndarray is not recommended because it will generate extra copies and increase memory consumption
  warnings.warn(

array([1245.7878, 1879.9492, 8498.966 , ..., 5719.738 , 5681.3813,
       5243.313 ], dtype=float32)

In [22]:
def show_status(data):
    print('max: {}'.format(np.max(data)))
    print('min: {}'.format(np.min(data)))
    print('ptp: {}'.format(np.ptp(data)))
    print('std: {}'.format(np.std(data)))
    print('mean: {}'.format(np.mean(data)))
    print('var: {}'.format(np.var(data)))

In [24]:
show_status(y_predictions)

max: 89463.125
min: -177.4859619140625
ptp: 89640.609375
std: 7349.2412109375
mean: 5911.19482421875
var: 54011344.0

In [23]:
result['price'] = y_predictions
temp = result['price']
temp[temp < 0] = 11
result['price'] = temp
show_status(result['price'])

max: 89463.125
min: 1.3741936683654785
ptp: 89461.75
std: 7349.19873046875
mean: 5911.23828125
var: 54010720.0

<ipython-input-23-77b515c3bf78>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp[temp < 0] = 11

In [25]:
result.to_csv('../05_prediction_result/xgb_predictions_v2.csv')

训练和测试数据保存

In [26]:
import pickle
train_data.to_pickle('../02_user_data/train_v2.pk')
test_data.to_pickle('../02_user_data/test_v2.pk')